// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: games.sql

package qg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceGames = `-- name: AdvanceGames :many
WITH candidates AS (
  SELECT game_id, stage
  FROM game_status
  WHERE (stage = 'lobby' OR stage = 'submit' OR stage = 'watch')
    AND due_at <= now()
  ORDER BY due_at ASC, game_id
  FOR UPDATE SKIP LOCKED
  LIMIT $1
),
upd AS (
  UPDATE game_status gs
  SET next_enqueue_at = now() + ($2::interval)
  FROM candidates c
  WHERE gs.game_id = c.game_id
  RETURNING gs.game_id, gs.theme_id, gs.stage, gs.round_n, gs.state_changed_at, gs.next_state_change_at, gs.next_enqueue_at, gs.due_at
)
SELECT game_id, theme_id, stage, round_n, state_changed_at, next_state_change_at, next_enqueue_at, due_at FROM upd
`

type AdvanceGamesRow struct {
	GameID            int64              `json:"game_id"`
	ThemeID           int64              `json:"theme_id"`
	Stage             GameStage          `json:"stage"`
	RoundN            int32              `json:"round_n"`
	StateChangedAt    pgtype.Timestamptz `json:"state_changed_at"`
	NextStateChangeAt pgtype.Timestamptz `json:"next_state_change_at"`
	NextEnqueueAt     pgtype.Timestamptz `json:"next_enqueue_at"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) AdvanceGames(ctx context.Context, batchSize int32, enqueueInterval pgtype.Interval) ([]AdvanceGamesRow, error) {
	rows, err := q.db.Query(ctx, advanceGames, batchSize, enqueueInterval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvanceGamesRow
	for rows.Next() {
		var i AdvanceGamesRow
		if err := rows.Scan(
			&i.GameID,
			&i.ThemeID,
			&i.Stage,
			&i.RoundN,
			&i.StateChangedAt,
			&i.NextStateChangeAt,
			&i.NextEnqueueAt,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPlayersInGame = `-- name: CountPlayersInGame :one
SELECT COUNT(*) AS player_count
FROM game_players
WHERE game_id = $1
`

func (q *Queries) CountPlayersInGame(ctx context.Context, gameID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayersInGame, gameID)
	var player_count int64
	err := row.Scan(&player_count)
	return player_count, err
}

const getGameAndPlayerLock = `-- name: GetGameAndPlayerLock :one
SELECT gs.game_id, gs.theme_id, gs.stage, gs.round_n, gs.state_changed_at, gs.next_state_change_at, gs.next_enqueue_at, gs.due_at, gp.player_id, gp.mode, gp.is_active, gp.joined_at
FROM game_players gp
JOIN game_status gs ON gs.game_id = gp.game_id
WHERE gp.game_id = $1
  AND gp.player_id = $2
  AND gs.stage = ANY($3::text[]::game_stage[])
FOR SHARE OF gs
`

type GetGameAndPlayerLockParams struct {
	GameID   int64    `json:"game_id"`
	PlayerID int64    `json:"player_id"`
	Stages   []string `json:"stages"`
}

type GetGameAndPlayerLockRow struct {
	GameID            int64              `json:"game_id"`
	ThemeID           int64              `json:"theme_id"`
	Stage             GameStage          `json:"stage"`
	RoundN            int32              `json:"round_n"`
	StateChangedAt    pgtype.Timestamptz `json:"state_changed_at"`
	NextStateChangeAt pgtype.Timestamptz `json:"next_state_change_at"`
	NextEnqueueAt     pgtype.Timestamptz `json:"next_enqueue_at"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	PlayerID          int64              `json:"player_id"`
	Mode              PlayerGameMode     `json:"mode"`
	IsActive          pgtype.Bool        `json:"is_active"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetGameAndPlayerLock(ctx context.Context, arg GetGameAndPlayerLockParams) (GetGameAndPlayerLockRow, error) {
	row := q.db.QueryRow(ctx, getGameAndPlayerLock, arg.GameID, arg.PlayerID, arg.Stages)
	var i GetGameAndPlayerLockRow
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.NextStateChangeAt,
		&i.NextEnqueueAt,
		&i.DueAt,
		&i.PlayerID,
		&i.Mode,
		&i.IsActive,
		&i.JoinedAt,
	)
	return i, err
}

const getGameLock = `-- name: GetGameLock :one
SELECT gs.game_id, gs.theme_id, gs.stage, gs.round_n, gs.state_changed_at, gs.next_state_change_at, gs.next_enqueue_at, gs.due_at, 
  GREATEST(
    COALESCE((EXTRACT(EPOCH FROM (gs.next_state_change_at - now())) * 1000)::bigint, 0),
    0
  )::bigint AS remaining_ms
FROM game_players gp
JOIN game_status gs ON gs.game_id = gp.game_id
WHERE gp.game_id  = $1
  AND gp.player_id = $2
FOR SHARE OF gs
`

type GetGameLockRow struct {
	GameID            int64              `json:"game_id"`
	ThemeID           int64              `json:"theme_id"`
	Stage             GameStage          `json:"stage"`
	RoundN            int32              `json:"round_n"`
	StateChangedAt    pgtype.Timestamptz `json:"state_changed_at"`
	NextStateChangeAt pgtype.Timestamptz `json:"next_state_change_at"`
	NextEnqueueAt     pgtype.Timestamptz `json:"next_enqueue_at"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	RemainingMs       int64              `json:"remaining_ms"`
}

func (q *Queries) GetGameLock(ctx context.Context, gameID int64, playerID int64) (GetGameLockRow, error) {
	row := q.db.QueryRow(ctx, getGameLock, gameID, playerID)
	var i GetGameLockRow
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.NextStateChangeAt,
		&i.NextEnqueueAt,
		&i.DueAt,
		&i.RemainingMs,
	)
	return i, err
}

const getGameRounds = `-- name: GetGameRounds :many
SELECT r.theme_id, r.round_n, r.title, r.description, r.created_at 
FROM rounds r
JOIN games g ON g.theme_id = r.theme_id
WHERE g.id = $1
ORDER BY r.round_n
`

func (q *Queries) GetGameRounds(ctx context.Context, id int64) ([]Round, error) {
	rows, err := q.db.Query(ctx, getGameRounds, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ThemeID,
			&i.RoundN,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameStateLock = `-- name: GetGameStateLock :one
SELECT 
  gs.game_id, 
  gs.theme_id,
  gs.stage,
  gs.round_n,
  gs.state_changed_at,
  gs.next_state_change_at,
  gs.next_enqueue_at,
  GREATEST(
    COALESCE((EXTRACT(EPOCH FROM (gs.next_state_change_at - now())) * 1000)::bigint, 0),
    0
  )::bigint AS remaining_ms,
  GREATEST(
    COALESCE((EXTRACT(EPOCH FROM (now() - gs.state_changed_at)) * 1000)::bigint, 0),
    0
  )::bigint AS past_ms
FROM game_status gs
WHERE gs.game_id = $1 
FOR UPDATE
`

type GetGameStateLockRow struct {
	GameID            int64              `json:"game_id"`
	ThemeID           int64              `json:"theme_id"`
	Stage             GameStage          `json:"stage"`
	RoundN            int32              `json:"round_n"`
	StateChangedAt    pgtype.Timestamptz `json:"state_changed_at"`
	NextStateChangeAt pgtype.Timestamptz `json:"next_state_change_at"`
	NextEnqueueAt     pgtype.Timestamptz `json:"next_enqueue_at"`
	RemainingMs       int64              `json:"remaining_ms"`
	PastMs            int64              `json:"past_ms"`
}

func (q *Queries) GetGameStateLock(ctx context.Context, gameID int64) (GetGameStateLockRow, error) {
	row := q.db.QueryRow(ctx, getGameStateLock, gameID)
	var i GetGameStateLockRow
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.NextStateChangeAt,
		&i.NextEnqueueAt,
		&i.RemainingMs,
		&i.PastMs,
	)
	return i, err
}

const joinGame = `-- name: JoinGame :one
SELECT join_game(
  $1, 
  $2, 
  $3, 
  $4, 
  $5, 
  $6,
  $7
) AS game_id
`

type JoinGameParams struct {
	ThemeID           int64           `json:"theme_id"`
	PlayerID          int64           `json:"player_id"`
	LobbyStage        GameStage       `json:"lobby_stage"`
	LobbyStageClosed  pgtype.Interval `json:"lobby_stage_closed"`
	MaxPlayers        int32           `json:"max_players"`
	NextStageChangeIn pgtype.Interval `json:"next_stage_change_in"`
	Mode              PlayerGameMode  `json:"mode"`
}

func (q *Queries) JoinGame(ctx context.Context, arg JoinGameParams) (int64, error) {
	row := q.db.QueryRow(ctx, joinGame,
		arg.ThemeID,
		arg.PlayerID,
		arg.LobbyStage,
		arg.LobbyStageClosed,
		arg.MaxPlayers,
		arg.NextStageChangeIn,
		arg.Mode,
	)
	var game_id int64
	err := row.Scan(&game_id)
	return game_id, err
}

const setCompletedStatus = `-- name: SetCompletedStatus :one
UPDATE game_status SET 
  stage = $1,
  next_state_change_at = NULL,
  next_enqueue_at = NULL,
  round_n = 0
WHERE game_id = $2 
RETURNING game_id, theme_id, stage, round_n, state_changed_at, next_state_change_at, next_enqueue_at, due_at
`

func (q *Queries) SetCompletedStatus(ctx context.Context, stage GameStage, gameID int64) (GameStatus, error) {
	row := q.db.QueryRow(ctx, setCompletedStatus, stage, gameID)
	var i GameStatus
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.NextStateChangeAt,
		&i.NextEnqueueAt,
		&i.DueAt,
	)
	return i, err
}

const updateGameMode = `-- name: UpdateGameMode :one
UPDATE game_players 
SET mode = $3
WHERE game_id = $1 AND player_id = $2
RETURNING game_id, player_id, mode, is_active, joined_at
`

type UpdateGameModeParams struct {
	GameID   int64          `json:"game_id"`
	PlayerID int64          `json:"player_id"`
	Mode     PlayerGameMode `json:"mode"`
}

func (q *Queries) UpdateGameMode(ctx context.Context, arg UpdateGameModeParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, updateGameMode, arg.GameID, arg.PlayerID, arg.Mode)
	var i GamePlayer
	err := row.Scan(
		&i.GameID,
		&i.PlayerID,
		&i.Mode,
		&i.IsActive,
		&i.JoinedAt,
	)
	return i, err
}

const updateGameStatus = `-- name: UpdateGameStatus :one
UPDATE game_status SET 
  stage = $1, 
  next_state_change_at = now() + ($2::interval),
  round_n = $3
WHERE game_id = $4 
RETURNING game_id, theme_id, stage, round_n, state_changed_at, next_state_change_at, next_enqueue_at, due_at, 
  GREATEST(
    (EXTRACT(EPOCH FROM (next_state_change_at - now())) * 1000)::bigint,
    0
  )::bigint AS remaining_ms
`

type UpdateGameStatusParams struct {
	Stage       GameStage       `json:"stage"`
	NextStateIn pgtype.Interval `json:"next_state_in"`
	RoundN      int32           `json:"round_n"`
	GameID      int64           `json:"game_id"`
}

type UpdateGameStatusRow struct {
	GameID            int64              `json:"game_id"`
	ThemeID           int64              `json:"theme_id"`
	Stage             GameStage          `json:"stage"`
	RoundN            int32              `json:"round_n"`
	StateChangedAt    pgtype.Timestamptz `json:"state_changed_at"`
	NextStateChangeAt pgtype.Timestamptz `json:"next_state_change_at"`
	NextEnqueueAt     pgtype.Timestamptz `json:"next_enqueue_at"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	RemainingMs       int64              `json:"remaining_ms"`
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) (UpdateGameStatusRow, error) {
	row := q.db.QueryRow(ctx, updateGameStatus,
		arg.Stage,
		arg.NextStateIn,
		arg.RoundN,
		arg.GameID,
	)
	var i UpdateGameStatusRow
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.NextStateChangeAt,
		&i.NextEnqueueAt,
		&i.DueAt,
		&i.RemainingMs,
	)
	return i, err
}

const updateRemainingTime = `-- name: UpdateRemainingTime :one
UPDATE game_status SET 
  next_state_change_at = now() + ($1::interval)
WHERE game_id = $2 
RETURNING game_id, theme_id, stage, round_n, state_changed_at, next_state_change_at, next_enqueue_at, due_at
`

func (q *Queries) UpdateRemainingTime(ctx context.Context, nextStateIn pgtype.Interval, gameID int64) (GameStatus, error) {
	row := q.db.QueryRow(ctx, updateRemainingTime, nextStateIn, gameID)
	var i GameStatus
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.NextStateChangeAt,
		&i.NextEnqueueAt,
		&i.DueAt,
	)
	return i, err
}
