// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: games.sql

package qg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlayersInGame = `-- name: CountPlayersInGame :one
SELECT COUNT(*) AS player_count
FROM game_players
WHERE game_id = $1
`

func (q *Queries) CountPlayersInGame(ctx context.Context, gameID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayersInGame, gameID)
	var player_count int64
	err := row.Scan(&player_count)
	return player_count, err
}

const enqueueGame = `-- name: EnqueueGame :one
WITH cte AS (
  SELECT gu.game_id
  FROM game_updates gu
  WHERE gu.game_id = $1
  FOR UPDATE SKIP LOCKED
)
UPDATE game_updates g
SET enqueued_at = now()
FROM cte
WHERE g.game_id = cte.game_id
RETURNING g.game_id, g.update_key, g.next_game_update_at, g.enqueued_at
`

func (q *Queries) EnqueueGame(ctx context.Context, gameID int64) (GameUpdate, error) {
	row := q.db.QueryRow(ctx, enqueueGame, gameID)
	var i GameUpdate
	err := row.Scan(
		&i.GameID,
		&i.UpdateKey,
		&i.NextGameUpdateAt,
		&i.EnqueuedAt,
	)
	return i, err
}

const enqueueGames = `-- name: EnqueueGames :many
WITH cte AS (
  SELECT game_id
  FROM game_updates
  WHERE enqueued_at IS NULL
  FOR UPDATE SKIP LOCKED
)
UPDATE game_updates g
SET enqueued_at = now()
FROM cte
WHERE g.game_id = cte.game_id
RETURNING g.game_id, g.update_key, g.next_game_update_at, g.enqueued_at
`

func (q *Queries) EnqueueGames(ctx context.Context) ([]GameUpdate, error) {
	rows, err := q.db.Query(ctx, enqueueGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameUpdate
	for rows.Next() {
		var i GameUpdate
		if err := rows.Scan(
			&i.GameID,
			&i.UpdateKey,
			&i.NextGameUpdateAt,
			&i.EnqueuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameLock = `-- name: GetGameLock :one
SELECT 
  gs.game_id, gs.theme_id, gs.stage, gs.round_n, gs.state_changed_at, gs.update_key, gs.next_game_update_at,
  GREATEST(
    COALESCE((EXTRACT(EPOCH FROM (gs.next_game_update_at - now())) * 1000)::bigint, 0),
    0
  )::bigint AS remaining_ms,
  GREATEST(
    COALESCE((EXTRACT(EPOCH FROM (now() - gs.state_changed_at)) * 1000)::bigint, 0),
    0
  )::bigint AS past_ms
FROM game_status gs
WHERE gs.game_id = $1 
  AND ($2::UUID IS NULL OR gs.update_key = $2::UUID)
FOR UPDATE
`

type GetGameLockRow struct {
	GameID           int64              `json:"game_id"`
	ThemeID          int64              `json:"theme_id"`
	Stage            GameStage          `json:"stage"`
	RoundN           int32              `json:"round_n"`
	StateChangedAt   pgtype.Timestamptz `json:"state_changed_at"`
	UpdateKey        pgtype.UUID        `json:"update_key"`
	NextGameUpdateAt pgtype.Timestamptz `json:"next_game_update_at"`
	RemainingMs      int64              `json:"remaining_ms"`
	PastMs           int64              `json:"past_ms"`
}

func (q *Queries) GetGameLock(ctx context.Context, gameID int64, updateKey pgtype.UUID) (GetGameLockRow, error) {
	row := q.db.QueryRow(ctx, getGameLock, gameID, updateKey)
	var i GetGameLockRow
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.UpdateKey,
		&i.NextGameUpdateAt,
		&i.RemainingMs,
		&i.PastMs,
	)
	return i, err
}

const getGameRounds = `-- name: GetGameRounds :many
SELECT r.theme_id, r.round_n, r.title, r.description, r.created_at 
FROM rounds r
JOIN games g ON g.theme_id = r.theme_id
WHERE g.id = $1
ORDER BY r.round_n
`

func (q *Queries) GetGameRounds(ctx context.Context, id int64) ([]Round, error) {
	rows, err := q.db.Query(ctx, getGameRounds, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ThemeID,
			&i.RoundN,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGameShareLock = `-- name: GetGameShareLock :one
SELECT gs.game_id, gs.theme_id, gs.stage, gs.round_n, gs.state_changed_at, gs.update_key, gs.next_game_update_at, gp.player_id, gp.mode, gp.is_active, gp.joined_at,
  GREATEST(
    COALESCE((EXTRACT(EPOCH FROM (gs.next_game_update_at - now())) * 1000)::bigint, 0),
    0
  )::bigint AS remaining_ms,
  GREATEST(
    COALESCE((EXTRACT(EPOCH FROM (now() - gs.state_changed_at)) * 1000)::bigint, 0),
    0
  )::bigint AS past_ms
FROM game_players gp
JOIN game_status gs ON gs.game_id = gp.game_id
WHERE gp.game_id  = $1
  AND gp.player_id = $2
FOR SHARE OF gs
`

type GetGameShareLockRow struct {
	GameID           int64              `json:"game_id"`
	ThemeID          int64              `json:"theme_id"`
	Stage            GameStage          `json:"stage"`
	RoundN           int32              `json:"round_n"`
	StateChangedAt   pgtype.Timestamptz `json:"state_changed_at"`
	UpdateKey        pgtype.UUID        `json:"update_key"`
	NextGameUpdateAt pgtype.Timestamptz `json:"next_game_update_at"`
	PlayerID         int64              `json:"player_id"`
	Mode             PlayerGameMode     `json:"mode"`
	IsActive         pgtype.Bool        `json:"is_active"`
	JoinedAt         pgtype.Timestamptz `json:"joined_at"`
	RemainingMs      int64              `json:"remaining_ms"`
	PastMs           int64              `json:"past_ms"`
}

func (q *Queries) GetGameShareLock(ctx context.Context, gameID int64, playerID int64) (GetGameShareLockRow, error) {
	row := q.db.QueryRow(ctx, getGameShareLock, gameID, playerID)
	var i GetGameShareLockRow
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.UpdateKey,
		&i.NextGameUpdateAt,
		&i.PlayerID,
		&i.Mode,
		&i.IsActive,
		&i.JoinedAt,
		&i.RemainingMs,
		&i.PastMs,
	)
	return i, err
}

const joinGame = `-- name: JoinGame :one
SELECT join_game(
  $1, 
  $2, 
  $3, 
  $4,
  $5, 
  $6
) AS game_id
`

type JoinGameParams struct {
	ThemeID          int64           `json:"theme_id"`
	PlayerID         int64           `json:"player_id"`
	LobbyStage       GameStage       `json:"lobby_stage"`
	NextGameUpdateIn pgtype.Interval `json:"next_game_update_in"`
	MaxPlayers       int32           `json:"max_players"`
	Mode             PlayerGameMode  `json:"mode"`
}

func (q *Queries) JoinGame(ctx context.Context, arg JoinGameParams) (int64, error) {
	row := q.db.QueryRow(ctx, joinGame,
		arg.ThemeID,
		arg.PlayerID,
		arg.LobbyStage,
		arg.NextGameUpdateIn,
		arg.MaxPlayers,
		arg.Mode,
	)
	var game_id int64
	err := row.Scan(&game_id)
	return game_id, err
}

const setCompletedStatus = `-- name: SetCompletedStatus :one
UPDATE game_status SET 
  stage = $1,
  next_state_change_at = NULL,
  next_enqueue_at = NULL,
  round_n = 0
WHERE game_id = $2 
RETURNING game_id, theme_id, stage, round_n, state_changed_at, update_key, next_game_update_at
`

func (q *Queries) SetCompletedStatus(ctx context.Context, stage GameStage, gameID int64) (GameStatus, error) {
	row := q.db.QueryRow(ctx, setCompletedStatus, stage, gameID)
	var i GameStatus
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.UpdateKey,
		&i.NextGameUpdateAt,
	)
	return i, err
}

const updateGameMode = `-- name: UpdateGameMode :one
UPDATE game_players 
SET mode = $3
WHERE game_id = $1 AND player_id = $2
RETURNING game_id, player_id, mode, is_active, joined_at
`

type UpdateGameModeParams struct {
	GameID   int64          `json:"game_id"`
	PlayerID int64          `json:"player_id"`
	Mode     PlayerGameMode `json:"mode"`
}

func (q *Queries) UpdateGameMode(ctx context.Context, arg UpdateGameModeParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, updateGameMode, arg.GameID, arg.PlayerID, arg.Mode)
	var i GamePlayer
	err := row.Scan(
		&i.GameID,
		&i.PlayerID,
		&i.Mode,
		&i.IsActive,
		&i.JoinedAt,
	)
	return i, err
}

const updateGameStatus = `-- name: UpdateGameStatus :one
UPDATE game_status SET 
  stage = $1, 
  state_changed_at = now(),
  round_n = $2,
  next_game_update_at = now() + $3::interval,
  update_key = uuid_generate_v1mc()
WHERE game_id = $4 
RETURNING game_id, theme_id, stage, round_n, state_changed_at, update_key, next_game_update_at
`

type UpdateGameStatusParams struct {
	Stage            GameStage       `json:"stage"`
	RoundN           int32           `json:"round_n"`
	NextGameUpdateIn pgtype.Interval `json:"next_game_update_in"`
	GameID           int64           `json:"game_id"`
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) (GameStatus, error) {
	row := q.db.QueryRow(ctx, updateGameStatus,
		arg.Stage,
		arg.RoundN,
		arg.NextGameUpdateIn,
		arg.GameID,
	)
	var i GameStatus
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.UpdateKey,
		&i.NextGameUpdateAt,
	)
	return i, err
}
