// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package qg

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Player struct {
	ID             int64              `json:"id"`
	TgID           int64              `json:"tg_id"`
	TgUsername     string             `json:"tg_username"`
	TgLanguageCode string             `json:"tg_language_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Theme struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Video struct {
	ID       int64              `json:"id"`
	PlayerID int64              `json:"player_id"`
	VideoUrl string             `json:"video_url"`
	Oembed   json.RawMessage    `json:"oembed"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
}

type VideoRequest struct {
	ID        int64              `json:"id"`
	Request   string             `json:"request"`
	ThemeID   int64              `json:"theme_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
