// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: players.sql

package qg

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (username) VALUES ($1) RETURNING id, username, created_at
`

type CreatePlayerParams struct {
	Username string `json:"username"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.Username)
	var i Player
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, username, created_at FROM players WHERE id = $1
`

type GetPlayerParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, arg.ID)
	var i Player
	err := row.Scan(&i.ID, &i.Username, &i.CreatedAt)
	return i, err
}
