// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: players.sql

package qg

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (tg_id, tg_username, tg_language_code) VALUES ($1, $2, $3) RETURNING id, tg_id, tg_username, tg_language_code, created_at
`

type CreatePlayerParams struct {
	TgID           int64  `json:"tg_id"`
	TgUsername     string `json:"tg_username"`
	TgLanguageCode string `json:"tg_language_code"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, arg.TgID, arg.TgUsername, arg.TgLanguageCode)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.TgUsername,
		&i.TgLanguageCode,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, tg_id, tg_username, tg_language_code, created_at FROM players WHERE id = $1
`

type GetPlayerParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, arg.ID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.TgUsername,
		&i.TgLanguageCode,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByTgId = `-- name: GetPlayerByTgId :one
SELECT id, tg_id, tg_username, tg_language_code, created_at FROM players WHERE tg_id = $1
`

type GetPlayerByTgIdParams struct {
	TgID int64 `json:"tg_id"`
}

func (q *Queries) GetPlayerByTgId(ctx context.Context, arg GetPlayerByTgIdParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByTgId, arg.TgID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.TgUsername,
		&i.TgLanguageCode,
		&i.CreatedAt,
	)
	return i, err
}
