// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package qg

import (
	"context"
)

type Querier interface {
	AddVideoByPlayerInGame(ctx context.Context, arg AddVideoByPlayerInGameParams) (Video, error)
	AddVideoToGame(ctx context.Context, arg AddVideoToGameParams) error
	AdvanceGames(ctx context.Context, arg AdvanceGamesParams) ([]AdvanceGamesRow, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	CreateVideoRequest(ctx context.Context, arg CreateVideoRequestParams) (VideoRequest, error)
	GetGameAndLock(ctx context.Context, arg GetGameAndLockParams) (Game, error)
	GetGameForPlayer(ctx context.Context, arg GetGameForPlayerParams) (GetGameForPlayerRow, error)
	GetPlayerByTgId(ctx context.Context, arg GetPlayerByTgIdParams) (Player, error)
	GetTheme(ctx context.Context, arg GetThemeParams) (Theme, error)
	GetVideo(ctx context.Context, arg GetVideoParams) (Video, error)
	GetVideoByPlayerInGame(ctx context.Context, arg GetVideoByPlayerInGameParams) (Video, error)
	GetVideoRequests(ctx context.Context, arg GetVideoRequestsParams) ([]VideoRequest, error)
	GetVideosByPlayer(ctx context.Context, arg GetVideosByPlayerParams) ([]Video, error)
	GetVideosToWatch(ctx context.Context, arg GetVideosToWatchParams) ([]Video, error)
	JoinGameForTheme(ctx context.Context, arg JoinGameForThemeParams) (int64, error)
	ListAllThemes(ctx context.Context) ([]Theme, error)
	ListThemes(ctx context.Context, arg ListThemesParams) ([]Theme, error)
	SetCompletedStatus(ctx context.Context, arg SetCompletedStatusParams) (Game, error)
	UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) (UpdateGameStatusRow, error)
}

var _ Querier = (*Queries)(nil)
