// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package qg

import (
	"context"
)

type Querier interface {
	AddVideoToPlayer(ctx context.Context, arg AddVideoToPlayerParams) (Video, error)
	AdvanceGames(ctx context.Context, arg AdvanceGamesParams) ([]AdvanceGamesRow, error)
	ChangeRemainingTime(ctx context.Context, arg ChangeRemainingTimeParams) (Game, error)
	CountPlayerInGame(ctx context.Context, arg CountPlayerInGameParams) (int64, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error)
	CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error)
	FetchGameAndLock(ctx context.Context, arg FetchGameAndLockParams) (FetchGameAndLockRow, error)
	FetchSubmittedVideosByPlayers(ctx context.Context, arg FetchSubmittedVideosByPlayersParams) ([]FetchSubmittedVideosByPlayersRow, error)
	FetchVotesByPlayers(ctx context.Context, arg FetchVotesByPlayersParams) ([]FetchVotesByPlayersRow, error)
	FindGameVideoForVote(ctx context.Context, arg FindGameVideoForVoteParams) (Game, error)
	FindGameWithPlayer(ctx context.Context, arg FindGameWithPlayerParams) (Game, error)
	GetGameForPlayer(ctx context.Context, arg GetGameForPlayerParams) (GetGameForPlayerRow, error)
	GetGameRounds(ctx context.Context, arg GetGameRoundsParams) ([]Round, error)
	GetPlayerByTgId(ctx context.Context, arg GetPlayerByTgIdParams) (Player, error)
	GetTheme(ctx context.Context, arg GetThemeParams) (Theme, error)
	GetVideo(ctx context.Context, arg GetVideoParams) (Video, error)
	GetVideosByPlayer(ctx context.Context, arg GetVideosByPlayerParams) ([]Video, error)
	GetVideosToWatch(ctx context.Context, arg GetVideosToWatchParams) ([]GetVideosToWatchRow, error)
	JoinGameForTheme(ctx context.Context, arg JoinGameForThemeParams) (int64, error)
	ListAllThemes(ctx context.Context) ([]Theme, error)
	ListThemes(ctx context.Context, arg ListThemesParams) ([]Theme, error)
	SetCompletedStatus(ctx context.Context, arg SetCompletedStatusParams) (Game, error)
	TestAddPlayerToGame(ctx context.Context, arg TestAddPlayerToGameParams) (GamePlayer, error)
	TestCreateGame(ctx context.Context, arg TestCreateGameParams) (Game, error)
	TestGetGameById(ctx context.Context, arg TestGetGameByIdParams) (Game, error)
	UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) (UpdateGameStatusRow, error)
	UpsertGameVideoIfOwned(ctx context.Context, arg UpsertGameVideoIfOwnedParams) (GameVideo, error)
	VoteForVideo(ctx context.Context, arg VoteForVideoParams) (GameVote, error)
}

var _ Querier = (*Queries)(nil)
