// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package qg

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddVideoToPlayer(ctx context.Context, arg AddVideoToPlayerParams) (Video, error)
	CountPlayersInGame(ctx context.Context, gameID int64) (int64, error)
	CreateFinalResult(ctx context.Context, gameID int64, result json.RawMessage) (GameFinalResult, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error)
	CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error)
	EnqueueGame(ctx context.Context, gameID int64) (GameUpdate, error)
	EnqueueGames(ctx context.Context) ([]GameUpdate, error)
	GetFinalResult(ctx context.Context, gameID int64, playerID int64) (GameFinalResult, error)
	GetGameLock(ctx context.Context, gameID int64, updateKey pgtype.UUID) (GetGameLockRow, error)
	GetGameRounds(ctx context.Context, gameID int64) ([]Round, error)
	GetGameShareLock(ctx context.Context, gameID int64, playerID int64) (GetGameShareLockRow, error)
	GetGameVideoShareLock(ctx context.Context, gameVideoID int64, playerID int64) (GetGameVideoShareLockRow, error)
	GetPlayerByTgId(ctx context.Context, tgID int64) (Player, error)
	GetRounds(ctx context.Context, themeID int64) ([]Round, error)
	GetSubmittedVideosByPlayers(ctx context.Context, gameID int64, roundN int32) ([]GetSubmittedVideosByPlayersRow, error)
	GetTheme(ctx context.Context, id int64) (Theme, error)
	GetVideosByPlayer(ctx context.Context, playerID int64) ([]Video, error)
	GetVideosToWatch(ctx context.Context, arg GetVideosToWatchParams) ([]GetVideosToWatchRow, error)
	GetVotes(ctx context.Context, gameID int64) ([]GetVotesRow, error)
	GetVotesForRound(ctx context.Context, gameID int64, roundN int32) ([]GetVotesForRoundRow, error)
	JoinGame(ctx context.Context, arg JoinGameParams) (int64, error)
	ListAllThemes(ctx context.Context) ([]Theme, error)
	ListThemes(ctx context.Context, limit int32, offset int32) ([]Theme, error)
	TestAddPlayerToGame(ctx context.Context, arg TestAddPlayerToGameParams) (GamePlayer, error)
	TestCreateGame(ctx context.Context, themeID int64) (Game, error)
	TestCreateGameStatus(ctx context.Context, arg TestCreateGameStatusParams) (GameStatus, error)
	TestCreateTheme(ctx context.Context, title string, mode GameMode) (Theme, error)
	TestGetGameById(ctx context.Context, id int64) (Game, error)
	TestGetGameStatusById(ctx context.Context, gameID int64) (TestGetGameStatusByIdRow, error)
	TestUpdateGameStage(ctx context.Context, stage GameStage, gameID int64) (GameStatus, error)
	TestUpdateGameStageAndUpdateAt(ctx context.Context, arg TestUpdateGameStageAndUpdateAtParams) (GameStatus, error)
	TestUpdatePlayerMode(ctx context.Context, playerID int64, mode PlayerGameMode) (GamePlayer, error)
	UpdateGameMode(ctx context.Context, arg UpdateGameModeParams) (GamePlayer, error)
	UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) (UpdateGameStatusRow, error)
	UpdateGameStatusComplete(ctx context.Context, stage GameStage, gameID int64) (GameStatus, error)
	UpsertGameVideoIfOwned(ctx context.Context, arg UpsertGameVideoIfOwnedParams) (GameVideo, error)
	VoteForVideo(ctx context.Context, arg VoteForVideoParams) (GameVote, error)
}

var _ Querier = (*Queries)(nil)
