// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tests.sql

package qg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const testAddPlayerToGame = `-- name: TestAddPlayerToGame :one
INSERT INTO game_players (
  game_id,
  player_id,
  mode
) VALUES (
  $1, $2, $3
)
RETURNING game_id, player_id, mode, is_active, joined_at
`

type TestAddPlayerToGameParams struct {
	GameID   int64          `json:"game_id"`
	PlayerID int64          `json:"player_id"`
	Mode     PlayerGameMode `json:"mode"`
}

func (q *Queries) TestAddPlayerToGame(ctx context.Context, arg TestAddPlayerToGameParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, testAddPlayerToGame, arg.GameID, arg.PlayerID, arg.Mode)
	var i GamePlayer
	err := row.Scan(
		&i.GameID,
		&i.PlayerID,
		&i.Mode,
		&i.IsActive,
		&i.JoinedAt,
	)
	return i, err
}

const testCreateGame = `-- name: TestCreateGame :one
INSERT INTO games (
  theme_id
) VALUES (
  $1
)
RETURNING id, theme_id, created_at, completed_at
`

func (q *Queries) TestCreateGame(ctx context.Context, themeID int64) (Game, error) {
	row := q.db.QueryRow(ctx, testCreateGame, themeID)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const testCreateGameStatus = `-- name: TestCreateGameStatus :one
INSERT INTO game_status (game_id, theme_id, stage, state_changed_at, update_key)
VALUES ($1, $2, $3, now(), uuid_generate_v1mc())
RETURNING game_id, theme_id, stage, round_n, state_changed_at, update_key, next_game_update_at
`

type TestCreateGameStatusParams struct {
	GameID  int64     `json:"game_id"`
	ThemeID int64     `json:"theme_id"`
	Stage   GameStage `json:"stage"`
}

func (q *Queries) TestCreateGameStatus(ctx context.Context, arg TestCreateGameStatusParams) (GameStatus, error) {
	row := q.db.QueryRow(ctx, testCreateGameStatus, arg.GameID, arg.ThemeID, arg.Stage)
	var i GameStatus
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.UpdateKey,
		&i.NextGameUpdateAt,
	)
	return i, err
}

const testGetGameById = `-- name: TestGetGameById :one
SELECT id, theme_id, created_at, completed_at FROM games WHERE id = $1
`

func (q *Queries) TestGetGameById(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRow(ctx, testGetGameById, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const testGetGameStatusById = `-- name: TestGetGameStatusById :one
SELECT game_id, theme_id, stage, round_n, state_changed_at, update_key, next_game_update_at,  
  GREATEST(
    COALESCE((EXTRACT(EPOCH FROM (now() - gs.state_changed_at)) * 1000)::bigint, 0),
    0
  )::bigint AS past_ms
FROM game_status 
WHERE game_id = $1
`

type TestGetGameStatusByIdRow struct {
	GameID           int64              `json:"game_id"`
	ThemeID          int64              `json:"theme_id"`
	Stage            GameStage          `json:"stage"`
	RoundN           int32              `json:"round_n"`
	StateChangedAt   pgtype.Timestamptz `json:"state_changed_at"`
	UpdateKey        pgtype.UUID        `json:"update_key"`
	NextGameUpdateAt pgtype.Timestamptz `json:"next_game_update_at"`
	PastMs           int64              `json:"past_ms"`
}

func (q *Queries) TestGetGameStatusById(ctx context.Context, gameID int64) (TestGetGameStatusByIdRow, error) {
	row := q.db.QueryRow(ctx, testGetGameStatusById, gameID)
	var i TestGetGameStatusByIdRow
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.UpdateKey,
		&i.NextGameUpdateAt,
		&i.PastMs,
	)
	return i, err
}

const testUpdateGameStage = `-- name: TestUpdateGameStage :one
UPDATE game_status
SET stage = $1
WHERE game_id = $2
RETURNING game_id, theme_id, stage, round_n, state_changed_at, update_key, next_game_update_at
`

func (q *Queries) TestUpdateGameStage(ctx context.Context, stage GameStage, gameID int64) (GameStatus, error) {
	row := q.db.QueryRow(ctx, testUpdateGameStage, stage, gameID)
	var i GameStatus
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.UpdateKey,
		&i.NextGameUpdateAt,
	)
	return i, err
}
