// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tests.sql

package qg

import (
	"context"
)

const testAddPlayerToGame = `-- name: TestAddPlayerToGame :one
INSERT INTO game_players (
  game_id,
  player_id
) VALUES (
  $1, $2
)
RETURNING game_id, player_id, mode, is_active, joined_at
`

func (q *Queries) TestAddPlayerToGame(ctx context.Context, gameID int64, playerID int64) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, testAddPlayerToGame, gameID, playerID)
	var i GamePlayer
	err := row.Scan(
		&i.GameID,
		&i.PlayerID,
		&i.Mode,
		&i.IsActive,
		&i.JoinedAt,
	)
	return i, err
}

const testCreateGame = `-- name: TestCreateGame :one
INSERT INTO games (
  theme_id
) VALUES (
  $1
)
RETURNING id, theme_id, created_at
`

func (q *Queries) TestCreateGame(ctx context.Context, themeID int64) (Game, error) {
	row := q.db.QueryRow(ctx, testCreateGame, themeID)
	var i Game
	err := row.Scan(&i.ID, &i.ThemeID, &i.CreatedAt)
	return i, err
}

const testGetGameById = `-- name: TestGetGameById :one
SELECT id, theme_id, created_at from games where id = $1
`

func (q *Queries) TestGetGameById(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRow(ctx, testGetGameById, id)
	var i Game
	err := row.Scan(&i.ID, &i.ThemeID, &i.CreatedAt)
	return i, err
}
