// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: themes.sql

package qg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (round_n, title, description, theme_id) VALUES ($1, $2, $3, $4) RETURNING theme_id, round_n, title, description, created_at
`

type CreateRoundParams struct {
	RoundN      int32       `json:"round_n"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	ThemeID     int64       `json:"theme_id"`
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, createRound,
		arg.RoundN,
		arg.Title,
		arg.Description,
		arg.ThemeID,
	)
	var i Round
	err := row.Scan(
		&i.ThemeID,
		&i.RoundN,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (title, description, mode) VALUES ($1, $2, $3) RETURNING id, title, description, mode, created_at
`

type CreateThemeParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Mode        GameMode    `json:"mode"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, createTheme, arg.Title, arg.Description, arg.Mode)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const getRounds = `-- name: GetRounds :many
SELECT theme_id, round_n, title, description, created_at FROM rounds WHERE theme_id = $1 ORDER BY round_n
`

func (q *Queries) GetRounds(ctx context.Context, themeID int64) ([]Round, error) {
	rows, err := q.db.Query(ctx, getRounds, themeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Round
	for rows.Next() {
		var i Round
		if err := rows.Scan(
			&i.ThemeID,
			&i.RoundN,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTheme = `-- name: GetTheme :one
SELECT id, title, description, mode, created_at FROM themes WHERE id = $1
`

func (q *Queries) GetTheme(ctx context.Context, id int64) (Theme, error) {
	row := q.db.QueryRow(ctx, getTheme, id)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const listAllThemes = `-- name: ListAllThemes :many
SELECT id, title, description, mode, created_at FROM themes ORDER BY created_at
`

func (q *Queries) ListAllThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listAllThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Mode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemes = `-- name: ListThemes :many
SELECT id, title, description, mode, created_at FROM themes ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

func (q *Queries) ListThemes(ctx context.Context, limit int32, offset int32) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listThemes, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Mode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
