// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: themes.sql

package qg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (round_n, title, description, theme_id) VALUES ($1, $2, $3, $4) RETURNING round_n, title, description, theme_id, created_at
`

type CreateRoundParams struct {
	RoundN      int32       `json:"round_n"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	ThemeID     int64       `json:"theme_id"`
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRow(ctx, createRound,
		arg.RoundN,
		arg.Title,
		arg.Description,
		arg.ThemeID,
	)
	var i Round
	err := row.Scan(
		&i.RoundN,
		&i.Title,
		&i.Description,
		&i.ThemeID,
		&i.CreatedAt,
	)
	return i, err
}

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (title, description) VALUES ($1, $2) RETURNING id, title, description, created_at
`

type CreateThemeParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, createTheme, arg.Title, arg.Description)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTheme = `-- name: GetTheme :one
SELECT id, title, description, created_at FROM themes WHERE id = $1
`

type GetThemeParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetTheme(ctx context.Context, arg GetThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, getTheme, arg.ID)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAllThemes = `-- name: ListAllThemes :many
SELECT id, title, description, created_at FROM themes ORDER BY created_at
`

func (q *Queries) ListAllThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listAllThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemes = `-- name: ListThemes :many
SELECT id, title, description, created_at FROM themes ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListThemesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListThemes(ctx context.Context, arg ListThemesParams) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listThemes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
