// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: videos.sql

package qg

import (
	"context"
	"encoding/json"
)

const addVideoToPlayer = `-- name: AddVideoToPlayer :one
SELECT id, video_url, oembed, added_at, updated_at FROM add_video_for_player($1, $2, $3)
`

type AddVideoToPlayerParams struct {
	PPlayerID int64           `json:"p_player_id"`
	PVideoUrl string          `json:"p_video_url"`
	POembed   json.RawMessage `json:"p_oembed"`
}

func (q *Queries) AddVideoToPlayer(ctx context.Context, arg AddVideoToPlayerParams) (Video, error) {
	row := q.db.QueryRow(ctx, addVideoToPlayer, arg.PPlayerID, arg.PVideoUrl, arg.POembed)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoUrl,
		&i.Oembed,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, video_url, oembed, added_at, updated_at FROM videos WHERE id = $1
`

type GetVideoParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetVideo(ctx context.Context, arg GetVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoUrl,
		&i.Oembed,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideosByPlayer = `-- name: GetVideosByPlayer :many
SELECT v.id, v.video_url, v.oembed, v.added_at, v.updated_at 
FROM videos AS v
JOIN player_videos AS pv ON pv.video_id = v.id
WHERE pv.player_id = $1
`

type GetVideosByPlayerParams struct {
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) GetVideosByPlayer(ctx context.Context, arg GetVideosByPlayerParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByPlayer, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.VideoUrl,
			&i.Oembed,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosToWatch = `-- name: GetVideosToWatch :many
SELECT v.id, v.video_url, v.oembed, v.added_at, v.updated_at
FROM game_videos gv
JOIN videos v
  ON v.id = gv.video_id
WHERE gv.game_id = $1
  AND EXISTS (
    SELECT 1
    FROM game_players gp
    WHERE gp.game_id  = $1
      AND gp.player_id = $2
  )
ORDER BY gv.submitted_at
`

type GetVideosToWatchParams struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) GetVideosToWatch(ctx context.Context, arg GetVideosToWatchParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosToWatch, arg.GameID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.VideoUrl,
			&i.Oembed,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGameVideoIfOwned = `-- name: UpsertGameVideoIfOwned :one
INSERT INTO game_videos (game_id, player_id, video_id, request_id)
SELECT $1, $2, $3, $4
WHERE
  -- player owns the video
  EXISTS (
    SELECT 1
    FROM player_videos pv
    WHERE pv.player_id = $2
      AND pv.video_id  = $3
  )
  -- request and game share the same theme
  AND EXISTS (
    SELECT 1
    FROM games g
    JOIN video_requests vr
      ON vr.id = $4
    AND vr.theme_id = g.theme_id
    WHERE g.id = $1
  )
ON CONFLICT ON CONSTRAINT unique_player_game_request
DO UPDATE
SET video_id     = EXCLUDED.video_id,
    submitted_at = now()
RETURNING game_id, player_id, video_id, request_id, submitted_at
`

type UpsertGameVideoIfOwnedParams struct {
	GameID    int64 `json:"game_id"`
	PlayerID  int64 `json:"player_id"`
	VideoID   int64 `json:"video_id"`
	RequestID int64 `json:"request_id"`
}

func (q *Queries) UpsertGameVideoIfOwned(ctx context.Context, arg UpsertGameVideoIfOwnedParams) (GameVideo, error) {
	row := q.db.QueryRow(ctx, upsertGameVideoIfOwned,
		arg.GameID,
		arg.PlayerID,
		arg.VideoID,
		arg.RequestID,
	)
	var i GameVideo
	err := row.Scan(
		&i.GameID,
		&i.PlayerID,
		&i.VideoID,
		&i.RequestID,
		&i.SubmittedAt,
	)
	return i, err
}
