// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: videos.sql

package qg

import (
	"context"
	"encoding/json"
)

const addVideoToGame = `-- name: AddVideoToGame :exec
INSERT INTO game_videos (game_id, player_id, video_id)
SELECT $1, $2, $3
FROM player_videos pv
WHERE pv.player_id = $2
  AND pv.video_id  = $3
ON CONFLICT (game_id, player_id)
DO UPDATE
SET video_id     = EXCLUDED.video_id,
    submitted_at = now()
`

type AddVideoToGameParams struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
	VideoID  int64 `json:"video_id"`
}

func (q *Queries) AddVideoToGame(ctx context.Context, arg AddVideoToGameParams) error {
	_, err := q.db.Exec(ctx, addVideoToGame, arg.GameID, arg.PlayerID, arg.VideoID)
	return err
}

const addVideoToPlayer = `-- name: AddVideoToPlayer :one
INSERT INTO player_videos (player_id, video_id) 
VALUES ($1, $2) 
ON CONFLICT (player_id, video_id) DO UPDATE
  SET added_at = now()
RETURNING player_id, video_id, added_at
`

type AddVideoToPlayerParams struct {
	PlayerID int64 `json:"player_id"`
	VideoID  int64 `json:"video_id"`
}

func (q *Queries) AddVideoToPlayer(ctx context.Context, arg AddVideoToPlayerParams) (PlayerVideo, error) {
	row := q.db.QueryRow(ctx, addVideoToPlayer, arg.PlayerID, arg.VideoID)
	var i PlayerVideo
	err := row.Scan(&i.PlayerID, &i.VideoID, &i.AddedAt)
	return i, err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (video_url, oembed) 
VALUES ($1, $2) 
ON CONFLICT (video_url) DO UPDATE
  SET video_url  = EXCLUDED.video_url,
      updated_at = now()
RETURNING id, video_url, oembed, added_at, updated_at
`

type CreateVideoParams struct {
	VideoUrl string          `json:"video_url"`
	Oembed   json.RawMessage `json:"oembed"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.VideoUrl, arg.Oembed)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoUrl,
		&i.Oembed,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, video_url, oembed, added_at, updated_at FROM videos WHERE id = $1
`

type GetVideoParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetVideo(ctx context.Context, arg GetVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoUrl,
		&i.Oembed,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoByPlayerInGame = `-- name: GetVideoByPlayerInGame :one
SELECT v.id, v.video_url, v.oembed, v.added_at, v.updated_at
FROM videos AS v
JOIN player_videos AS pv
  ON pv.video_id = v.id
JOIN game_players AS gp
  ON gp.player_id = pv.player_id
 AND gp.game_id   = $1
WHERE v.id         = $2
  AND pv.player_id = $3
LIMIT 1
`

type GetVideoByPlayerInGameParams struct {
	GameID   int64 `json:"game_id"`
	ID       int64 `json:"id"`
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) GetVideoByPlayerInGame(ctx context.Context, arg GetVideoByPlayerInGameParams) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByPlayerInGame, arg.GameID, arg.ID, arg.PlayerID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.VideoUrl,
		&i.Oembed,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideosByPlayer = `-- name: GetVideosByPlayer :many
SELECT v.id, v.video_url, v.oembed, v.added_at, v.updated_at FROM videos AS v
JOIN player_videos AS pv ON pv.video_id = v.id
WHERE pv.player_id = $1
`

type GetVideosByPlayerParams struct {
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) GetVideosByPlayer(ctx context.Context, arg GetVideosByPlayerParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByPlayer, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.VideoUrl,
			&i.Oembed,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosToWatch = `-- name: GetVideosToWatch :many
SELECT v.id, v.video_url, v.oembed, v.added_at, v.updated_at
FROM game_videos gv
JOIN player_videos pv
  ON pv.player_id = gv.player_id
 AND pv.video_id  = gv.video_id
JOIN videos v
  ON v.id = gv.video_id
WHERE gv.game_id = $1
  AND EXISTS (
    SELECT 1
    FROM game_players gp
    WHERE gp.game_id  = $1
      AND gp.player_id = $2
  )
ORDER BY gv.submitted_at
`

type GetVideosToWatchParams struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) GetVideosToWatch(ctx context.Context, arg GetVideosToWatchParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosToWatch, arg.GameID, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.VideoUrl,
			&i.Oembed,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
