// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: votes.sql

package qg

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGameVideoShareLock = `-- name: GetGameVideoShareLock :one
SELECT 
  gs.game_id, gs.theme_id, gs.mode, gs.stage, gs.round_n, gs.state_changed_at, gs.update_key, gs.next_game_update_at,
  gv.id as game_video_id,
  gv.player_id,
  gv.video_id,
  gv.submitted_at
  FROM game_videos gv
  JOIN game_status gs ON gs.game_id = gv.game_id
  WHERE gv.id = $1
    AND gv.player_id <> $2 -- player can't vote for its own video
    AND EXISTS (
      SELECT 1
      FROM game_players gp
      WHERE gp.game_id = gv.game_id
        AND gp.player_id = $2
    ) 
FOR SHARE OF gs
`

type GetGameVideoShareLockRow struct {
	GameID           int64              `json:"game_id"`
	ThemeID          int64              `json:"theme_id"`
	Mode             GameMode           `json:"mode"`
	Stage            GameStage          `json:"stage"`
	RoundN           int32              `json:"round_n"`
	StateChangedAt   pgtype.Timestamptz `json:"state_changed_at"`
	UpdateKey        pgtype.UUID        `json:"update_key"`
	NextGameUpdateAt pgtype.Timestamptz `json:"next_game_update_at"`
	GameVideoID      int64              `json:"game_video_id"`
	PlayerID         int64              `json:"player_id"`
	VideoID          int64              `json:"video_id"`
	SubmittedAt      pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) GetGameVideoShareLock(ctx context.Context, gameVideoID int64, playerID int64) (GetGameVideoShareLockRow, error) {
	row := q.db.QueryRow(ctx, getGameVideoShareLock, gameVideoID, playerID)
	var i GetGameVideoShareLockRow
	err := row.Scan(
		&i.GameID,
		&i.ThemeID,
		&i.Mode,
		&i.Stage,
		&i.RoundN,
		&i.StateChangedAt,
		&i.UpdateKey,
		&i.NextGameUpdateAt,
		&i.GameVideoID,
		&i.PlayerID,
		&i.VideoID,
		&i.SubmittedAt,
	)
	return i, err
}

const getVotes = `-- name: GetVotes :many
WITH players AS (
  SELECT gp.player_id
  FROM game_players gp
  WHERE gp.game_id = $1
),
videos AS (
  SELECT gv.id AS game_video_id, gv.player_id AS author_id, gv.round_n
  FROM game_videos gv
  WHERE gv.game_id = $1
),
expected AS (
  SELECT p.player_id, v.game_video_id, v.round_n, v.author_id
  FROM players p
  CROSS JOIN videos v
  WHERE p.player_id <> v.author_id
)
SELECT 
  e.player_id,
  e.game_video_id,
  e.round_n,
  e.author_id,
  gvt.value,
  gvt.voted_at
  FROM expected e
  LEFT JOIN game_votes gvt
    ON gvt.game_video_id = e.game_video_id
   AND gvt.player_id     = e.player_id
  ORDER BY e.round_n, e.game_video_id
`

type GetVotesRow struct {
	PlayerID    int64              `json:"player_id"`
	GameVideoID int64              `json:"game_video_id"`
	RoundN      int32              `json:"round_n"`
	AuthorID    int64              `json:"author_id"`
	Value       []byte             `json:"value"`
	VotedAt     pgtype.Timestamptz `json:"voted_at"`
}

func (q *Queries) GetVotes(ctx context.Context, gameID int64) ([]GetVotesRow, error) {
	rows, err := q.db.Query(ctx, getVotes, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVotesRow
	for rows.Next() {
		var i GetVotesRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.GameVideoID,
			&i.RoundN,
			&i.AuthorID,
			&i.Value,
			&i.VotedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotesForRound = `-- name: GetVotesForRound :many
WITH players AS (
  SELECT gp.player_id
  FROM game_players gp
  WHERE gp.game_id = $1
),
videos AS (
  SELECT gv.id AS game_video_id, gv.player_id AS author_id
  FROM game_videos gv
  WHERE gv.game_id = $1
    AND gv.round_n = $2
),
expected AS (
  SELECT p.player_id, v.game_video_id
  FROM players p
  CROSS JOIN videos v
  WHERE p.player_id <> v.author_id
)
SELECT 
  e.player_id,
  e.game_video_id,
  gvt.value,
  gvt.voted_at
  FROM expected e
  LEFT JOIN game_votes gvt
    ON gvt.game_video_id = e.game_video_id
   AND gvt.player_id     = e.player_id
`

type GetVotesForRoundRow struct {
	PlayerID    int64              `json:"player_id"`
	GameVideoID int64              `json:"game_video_id"`
	Value       []byte             `json:"value"`
	VotedAt     pgtype.Timestamptz `json:"voted_at"`
}

func (q *Queries) GetVotesForRound(ctx context.Context, gameID int64, roundN int32) ([]GetVotesForRoundRow, error) {
	rows, err := q.db.Query(ctx, getVotesForRound, gameID, roundN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVotesForRoundRow
	for rows.Next() {
		var i GetVotesForRoundRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.GameVideoID,
			&i.Value,
			&i.VotedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voteForVideo = `-- name: VoteForVideo :one
INSERT INTO game_votes (game_video_id, player_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (game_video_id, player_id)
DO UPDATE 
SET value = EXCLUDED.value, 
    voted_at = now()
RETURNING game_video_id, player_id, value, voted_at
`

type VoteForVideoParams struct {
	GameVideoID int64           `json:"game_video_id"`
	PlayerID    int64           `json:"player_id"`
	Value       json.RawMessage `json:"value"`
}

func (q *Queries) VoteForVideo(ctx context.Context, arg VoteForVideoParams) (GameVote, error) {
	row := q.db.QueryRow(ctx, voteForVideo, arg.GameVideoID, arg.PlayerID, arg.Value)
	var i GameVote
	err := row.Scan(
		&i.GameVideoID,
		&i.PlayerID,
		&i.Value,
		&i.VotedAt,
	)
	return i, err
}
