// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: votes.sql

package qg

import (
	"context"
)

const voteForVideo = `-- name: VoteForVideo :one
INSERT INTO game_votes (game_video_id, player_id, value)
VALUES ($1, $2, $3)
ON CONFLICT (game_video_id, player_id)
DO UPDATE 
SET value = EXCLUDED.value, 
    voted_at = now()
RETURNING game_video_id, player_id, value, voted_at
`

type VoteForVideoParams struct {
	GameVideoID int64     `json:"game_video_id"`
	PlayerID    int64     `json:"player_id"`
	Value       VoteValue `json:"value"`
}

func (q *Queries) VoteForVideo(ctx context.Context, arg VoteForVideoParams) (GameVote, error) {
	row := q.db.QueryRow(ctx, voteForVideo, arg.GameVideoID, arg.PlayerID, arg.Value)
	var i GameVote
	err := row.Scan(
		&i.GameVideoID,
		&i.PlayerID,
		&i.Value,
		&i.VotedAt,
	)
	return i, err
}
