// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: themes.sql

package q

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at
`

type CreateThemeParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, createTheme, arg.Name, arg.Description)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createVideoRequest = `-- name: CreateVideoRequest :one
INSERT INTO video_requests (request, theme_id) VALUES ($1, $2) RETURNING id, request, theme_id, created_at
`

type CreateVideoRequestParams struct {
	Request string `json:"request"`
	ThemeID int64  `json:"theme_id"`
}

func (q *Queries) CreateVideoRequest(ctx context.Context, arg CreateVideoRequestParams) (VideoRequest, error) {
	row := q.db.QueryRow(ctx, createVideoRequest, arg.Request, arg.ThemeID)
	var i VideoRequest
	err := row.Scan(
		&i.ID,
		&i.Request,
		&i.ThemeID,
		&i.CreatedAt,
	)
	return i, err
}

const getTheme = `-- name: GetTheme :one
SELECT id, name, description, created_at FROM themes WHERE id = $1
`

type GetThemeParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetTheme(ctx context.Context, arg GetThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, getTheme, arg.ID)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getVideoRequests = `-- name: GetVideoRequests :many
SELECT id, request, theme_id, created_at FROM video_requests WHERE theme_id = $1
`

type GetVideoRequestsParams struct {
	ThemeID int64 `json:"theme_id"`
}

func (q *Queries) GetVideoRequests(ctx context.Context, arg GetVideoRequestsParams) ([]VideoRequest, error) {
	rows, err := q.db.Query(ctx, getVideoRequests, arg.ThemeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoRequest
	for rows.Next() {
		var i VideoRequest
		if err := rows.Scan(
			&i.ID,
			&i.Request,
			&i.ThemeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllThemes = `-- name: ListAllThemes :many
SELECT id, name, description, created_at FROM themes ORDER BY created_at
`

func (q *Queries) ListAllThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listAllThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemes = `-- name: ListThemes :many
SELECT id, name, description, created_at FROM themes ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListThemesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListThemes(ctx context.Context, arg ListThemesParams) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listThemes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
