// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: game_players.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlayerToGame = `-- name: AddPlayerToGame :exec
INSERT INTO game_players (game_id, player_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPlayerToGameParams struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) AddPlayerToGame(ctx context.Context, arg AddPlayerToGameParams) error {
	_, err := q.db.Exec(ctx, addPlayerToGame, arg.GameID, arg.PlayerID)
	return err
}

const findLeastCrowdedGameByThemeAndStatuses = `-- name: FindLeastCrowdedGameByThemeAndStatuses :one
SELECT g.id, g.theme_id, g.status, g.created_at, COUNT(gp.player_id) AS player_count
FROM games AS g
LEFT JOIN game_players AS gp
  ON gp.game_id = g.id
WHERE g.theme_id = $1
  AND g.status = ANY(($2::text[])::game_status[])
GROUP BY g.id
ORDER BY player_count
LIMIT 1
`

type FindLeastCrowdedGameByThemeAndStatusesParams struct {
	ThemeID int64    `json:"theme_id"`
	Column2 []string `json:"column_2"`
}

type FindLeastCrowdedGameByThemeAndStatusesRow struct {
	ID          int64              `json:"id"`
	ThemeID     int64              `json:"theme_id"`
	Status      GameStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PlayerCount int64              `json:"player_count"`
}

func (q *Queries) FindLeastCrowdedGameByThemeAndStatuses(ctx context.Context, arg FindLeastCrowdedGameByThemeAndStatusesParams) (FindLeastCrowdedGameByThemeAndStatusesRow, error) {
	row := q.db.QueryRow(ctx, findLeastCrowdedGameByThemeAndStatuses, arg.ThemeID, arg.Column2)
	var i FindLeastCrowdedGameByThemeAndStatusesRow
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Status,
		&i.CreatedAt,
		&i.PlayerCount,
	)
	return i, err
}

const getPlayersInGame = `-- name: GetPlayersInGame :many
SELECT p.id, p.username, p.created_at
FROM players p
JOIN game_players gp ON p.id = gp.player_id
WHERE gp.game_id = $1
`

type GetPlayersInGameParams struct {
	GameID int64 `json:"game_id"`
}

func (q *Queries) GetPlayersInGame(ctx context.Context, arg GetPlayersInGameParams) ([]Player, error) {
	rows, err := q.db.Query(ctx, getPlayersInGame, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(&i.ID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isPlayerInGame = `-- name: IsPlayerInGame :one
SELECT EXISTS (
    SELECT 1 FROM game_players
    WHERE game_id = $1 AND player_id = $2
) AS exists
`

type IsPlayerInGameParams struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) IsPlayerInGame(ctx context.Context, arg IsPlayerInGameParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPlayerInGame, arg.GameID, arg.PlayerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
