// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: games.sql

package db

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (status)
VALUES ($1)
RETURNING id, created_at, status
`

func (q *Queries) CreateGame(ctx context.Context, status GameStatus) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, status)
	var i Game
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Status)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getAllGames = `-- name: GetAllGames :many
SELECT id, created_at, status FROM games ORDER BY created_at DESC
`

func (q *Queries) GetAllGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, getAllGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGame = `-- name: GetGame :one
SELECT id, created_at, status FROM games WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Status)
	return i, err
}

const updateGameStatus = `-- name: UpdateGameStatus :exec
UPDATE games SET status = $1 WHERE id = $2
`

type UpdateGameStatusParams struct {
	Status GameStatus `json:"status"`
	ID     int64      `json:"id"`
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) error {
	_, err := q.db.Exec(ctx, updateGameStatus, arg.Status, arg.ID)
	return err
}
