// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: game_players.sql

package db

import (
	"context"
)

const addPlayerToGame = `-- name: AddPlayerToGame :exec
INSERT INTO game_players (game_id, player_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPlayerToGameParams struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) AddPlayerToGame(ctx context.Context, arg AddPlayerToGameParams) error {
	_, err := q.db.Exec(ctx, addPlayerToGame, arg.GameID, arg.PlayerID)
	return err
}

const getPlayersInGame = `-- name: GetPlayersInGame :many
SELECT p.id, p.username
FROM players p
JOIN game_players gp ON p.id = gp.player_id
WHERE gp.game_id = $1
`

type GetPlayersInGameParams struct {
	GameID int64 `json:"game_id"`
}

type GetPlayersInGameRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) GetPlayersInGame(ctx context.Context, arg GetPlayersInGameParams) ([]GetPlayersInGameRow, error) {
	rows, err := q.db.Query(ctx, getPlayersInGame, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlayersInGameRow
	for rows.Next() {
		var i GetPlayersInGameRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isPlayerInGame = `-- name: IsPlayerInGame :one
SELECT EXISTS (
    SELECT 1 FROM game_players
    WHERE game_id = $1 AND player_id = $2
) AS exists
`

type IsPlayerInGameParams struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) IsPlayerInGame(ctx context.Context, arg IsPlayerInGameParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPlayerInGame, arg.GameID, arg.PlayerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
