// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (status, name, description)
VALUES ($1, $2, $3)
RETURNING id, status, name, description, created_at
`

type CreateGameParams struct {
	Status      GameStatus  `json:"status"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame, arg.Status, arg.Name, arg.Description)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :exec
DELETE FROM games WHERE id = $1
`

func (q *Queries) DeleteGame(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGame, id)
	return err
}

const getAllGames = `-- name: GetAllGames :many
SELECT id, status, name, description, created_at FROM games ORDER BY created_at DESC
`

func (q *Queries) GetAllGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, getAllGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGame = `-- name: GetGame :one
SELECT id, status, name, description, created_at FROM games WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id int64) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateGameStatus = `-- name: UpdateGameStatus :exec
UPDATE games SET status = $1 WHERE id = $2
`

type UpdateGameStatusParams struct {
	Status GameStatus `json:"status"`
	ID     int64      `json:"id"`
}

func (q *Queries) UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) error {
	_, err := q.db.Exec(ctx, updateGameStatus, arg.Status, arg.ID)
	return err
}
