// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type GameStatus string

const (
	GameStatusCreated    GameStatus = "created"
	GameStatusLobby      GameStatus = "lobby"
	GameStatusSubmitting GameStatus = "submitting"
	GameStatusVoting     GameStatus = "voting"
	GameStatusWinner     GameStatus = "winner"
	GameStatusComplete   GameStatus = "complete"
)

func (e *GameStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameStatus(s)
	case string:
		*e = GameStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GameStatus: %T", src)
	}
	return nil
}

type NullGameStatus struct {
	GameStatus GameStatus `json:"game_status"`
	Valid      bool       `json:"valid"` // Valid is true if GameStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GameStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameStatus), nil
}

type Game struct {
	ID        int64            `json:"id"`
	ThemeID   int64            `json:"theme_id"`
	Status    GameStatus       `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type GamePlayer struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
}

type Player struct {
	ID        int64            `json:"id"`
	Username  string           `json:"username"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Theme struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Video struct {
	ID          int64            `json:"id"`
	GameID      int64            `json:"game_id"`
	PlayerID    int64            `json:"player_id"`
	VideoUrl    string           `json:"video_url"`
	SubmittedAt pgtype.Timestamp `json:"submitted_at"`
}

type Vote struct {
	ID      int64            `json:"id"`
	GameID  int64            `json:"game_id"`
	VideoID int64            `json:"video_id"`
	VoterID int64            `json:"voter_id"`
	VotedAt pgtype.Timestamp `json:"voted_at"`
}
