// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: players.sql

package db

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (name) VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreatePlayer(ctx context.Context, name string) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer, name)
	var i Player
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, name FROM players WHERE id = $1
`

func (q *Queries) GetPlayer(ctx context.Context, id int32) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i Player
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
