// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPlayerToGame(ctx context.Context, arg AddPlayerToGameParams) error
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreatePlayer(ctx context.Context, username string) (Player, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	DeleteGame(ctx context.Context, id int64) error
	GetAllGames(ctx context.Context) ([]Game, error)
	GetAllPlayers(ctx context.Context) ([]Player, error)
	GetGame(ctx context.Context, id int64) (Game, error)
	GetPlayer(ctx context.Context, id int64) (Player, error)
	GetPlayersInGame(ctx context.Context, gameID int64) ([]GetPlayersInGameRow, error)
	GetVideosByGame(ctx context.Context, gameID pgtype.Int8) ([]Video, error)
	GetVideosByPlayer(ctx context.Context, arg GetVideosByPlayerParams) (Video, error)
	GetVoteCountsByVideo(ctx context.Context, gameID pgtype.Int8) ([]GetVoteCountsByVideoRow, error)
	GetVotesByGame(ctx context.Context, gameID pgtype.Int8) ([]Vote, error)
	GetWinningVideo(ctx context.Context, gameID pgtype.Int8) (GetWinningVideoRow, error)
	HasPlayerVoted(ctx context.Context, arg HasPlayerVotedParams) (bool, error)
	IsPlayerInGame(ctx context.Context, arg IsPlayerInGameParams) (bool, error)
	UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) error
}

var _ Querier = (*Queries)(nil)
