// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	// Blocks until acquired; auto-released when the current transaction ends.
	AcquireAdvisoryXactLock(ctx context.Context, arg AcquireAdvisoryXactLockParams) error
	AddPlayerToGame(ctx context.Context, arg AddPlayerToGameParams) error
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	DeleteGame(ctx context.Context, arg DeleteGameParams) error
	DeleteTheme(ctx context.Context, arg DeleteThemeParams) error
	FindLeastCrowdedGameByThemeAndStatuses(ctx context.Context, arg FindLeastCrowdedGameByThemeAndStatusesParams) (FindLeastCrowdedGameByThemeAndStatusesRow, error)
	GetAllGames(ctx context.Context) ([]Game, error)
	GetAllPlayers(ctx context.Context) ([]Player, error)
	GetGame(ctx context.Context, arg GetGameParams) (Game, error)
	GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error)
	GetPlayersInGame(ctx context.Context, arg GetPlayersInGameParams) ([]Player, error)
	GetThemeByID(ctx context.Context, arg GetThemeByIDParams) (Theme, error)
	GetVideosByGame(ctx context.Context, arg GetVideosByGameParams) ([]Video, error)
	GetVideosByPlayer(ctx context.Context, arg GetVideosByPlayerParams) (GetVideosByPlayerRow, error)
	GetVoteCountsByVideo(ctx context.Context, arg GetVoteCountsByVideoParams) ([]GetVoteCountsByVideoRow, error)
	GetVotesByGame(ctx context.Context, arg GetVotesByGameParams) ([]Vote, error)
	GetWinningVideo(ctx context.Context, arg GetWinningVideoParams) (GetWinningVideoRow, error)
	HasPlayerVoted(ctx context.Context, arg HasPlayerVotedParams) (bool, error)
	InvalidateOtherVideos(ctx context.Context, arg InvalidateOtherVideosParams) error
	InvalidateOtherVotes(ctx context.Context, arg InvalidateOtherVotesParams) error
	IsPlayerInGame(ctx context.Context, arg IsPlayerInGameParams) (bool, error)
	ListAllThemes(ctx context.Context) ([]Theme, error)
	ListThemes(ctx context.Context, arg ListThemesParams) ([]Theme, error)
	RemovePlayerFromGame(ctx context.Context, arg RemovePlayerFromGameParams) error
	SearchThemesByName(ctx context.Context, arg SearchThemesByNameParams) ([]Theme, error)
	UpdateGameStatus(ctx context.Context, arg UpdateGameStatusParams) (Game, error)
	UpdateTheme(ctx context.Context, arg UpdateThemeParams) (Theme, error)
}

var _ Querier = (*Queries)(nil)
