// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: submissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (game_id, player_id, video_url, submitted_at)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, player_id, video_url, submitted_at
`

type CreateSubmissionParams struct {
	GameID      pgtype.Int8      `json:"game_id"`
	PlayerID    pgtype.Int8      `json:"player_id"`
	VideoUrl    string           `json:"video_url"`
	SubmittedAt pgtype.Timestamp `json:"submitted_at"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.GameID,
		arg.PlayerID,
		arg.VideoUrl,
		arg.SubmittedAt,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.VideoUrl,
		&i.SubmittedAt,
	)
	return i, err
}

const getSubmissionByPlayer = `-- name: GetSubmissionByPlayer :one
SELECT id, game_id, player_id, video_url, submitted_at
FROM submissions
WHERE game_id = $1 AND player_id = $2
`

type GetSubmissionByPlayerParams struct {
	GameID   pgtype.Int8 `json:"game_id"`
	PlayerID pgtype.Int8 `json:"player_id"`
}

func (q *Queries) GetSubmissionByPlayer(ctx context.Context, arg GetSubmissionByPlayerParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByPlayer, arg.GameID, arg.PlayerID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.VideoUrl,
		&i.SubmittedAt,
	)
	return i, err
}

const getSubmissionsByGame = `-- name: GetSubmissionsByGame :many
SELECT id, game_id, player_id, video_url, submitted_at
FROM submissions
WHERE game_id = $1
`

func (q *Queries) GetSubmissionsByGame(ctx context.Context, gameID pgtype.Int8) ([]Submission, error) {
	rows, err := q.db.Query(ctx, getSubmissionsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.VideoUrl,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
