// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: themes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at
`

type CreateThemeParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, createTheme, arg.Name, arg.Description)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTheme = `-- name: DeleteTheme :exec
DELETE FROM themes WHERE id = $1
`

type DeleteThemeParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) DeleteTheme(ctx context.Context, arg DeleteThemeParams) error {
	_, err := q.db.Exec(ctx, deleteTheme, arg.ID)
	return err
}

const getThemeByID = `-- name: GetThemeByID :one
SELECT id, name, description, created_at FROM themes WHERE id = $1
`

type GetThemeByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetThemeByID(ctx context.Context, arg GetThemeByIDParams) (Theme, error) {
	row := q.db.QueryRow(ctx, getThemeByID, arg.ID)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAllThemes = `-- name: ListAllThemes :many
SELECT id, name, description, created_at FROM themes ORDER BY created_at
`

func (q *Queries) ListAllThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listAllThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemes = `-- name: ListThemes :many
SELECT id, name, description, created_at FROM themes ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListThemesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListThemes(ctx context.Context, arg ListThemesParams) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listThemes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchThemesByName = `-- name: SearchThemesByName :many
SELECT id, name, description, created_at FROM themes WHERE name ILIKE '%' || $1 || '%' ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type SearchThemesByNameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchThemesByName(ctx context.Context, arg SearchThemesByNameParams) ([]Theme, error) {
	rows, err := q.db.Query(ctx, searchThemesByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTheme = `-- name: UpdateTheme :one
UPDATE themes SET name = $1, description = $2 WHERE id = $3 RETURNING id, name, description, created_at
`

type UpdateThemeParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateTheme(ctx context.Context, arg UpdateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, updateTheme, arg.Name, arg.Description, arg.ID)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
