// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: videos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (game_id, player_id, video_url, is_actual)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, player_id, video_url, is_actual, submitted_at
`

type CreateVideoParams struct {
	GameID   int64  `json:"game_id"`
	PlayerID int64  `json:"player_id"`
	VideoUrl string `json:"video_url"`
	IsActual bool   `json:"is_actual"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.GameID,
		arg.PlayerID,
		arg.VideoUrl,
		arg.IsActual,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.VideoUrl,
		&i.IsActual,
		&i.SubmittedAt,
	)
	return i, err
}

const getVideosByGame = `-- name: GetVideosByGame :many
SELECT id, game_id, player_id, video_url, is_actual, submitted_at
FROM videos
WHERE game_id = $1
`

type GetVideosByGameParams struct {
	GameID int64 `json:"game_id"`
}

func (q *Queries) GetVideosByGame(ctx context.Context, arg GetVideosByGameParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByGame, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.VideoUrl,
			&i.IsActual,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosByPlayer = `-- name: GetVideosByPlayer :one
SELECT id, game_id, player_id, video_url, submitted_at
FROM videos
WHERE game_id = $1 AND player_id = $2
`

type GetVideosByPlayerParams struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
}

type GetVideosByPlayerRow struct {
	ID          int64              `json:"id"`
	GameID      int64              `json:"game_id"`
	PlayerID    int64              `json:"player_id"`
	VideoUrl    string             `json:"video_url"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) GetVideosByPlayer(ctx context.Context, arg GetVideosByPlayerParams) (GetVideosByPlayerRow, error) {
	row := q.db.QueryRow(ctx, getVideosByPlayer, arg.GameID, arg.PlayerID)
	var i GetVideosByPlayerRow
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.VideoUrl,
		&i.SubmittedAt,
	)
	return i, err
}

const invalidateOtherVideos = `-- name: InvalidateOtherVideos :exec
UPDATE videos SET is_actual = FALSE WHERE game_id = $1 AND player_id = $2 AND id <> $3
`

type InvalidateOtherVideosParams struct {
	GameID   int64 `json:"game_id"`
	PlayerID int64 `json:"player_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) InvalidateOtherVideos(ctx context.Context, arg InvalidateOtherVideosParams) error {
	_, err := q.db.Exec(ctx, invalidateOtherVideos, arg.GameID, arg.PlayerID, arg.ID)
	return err
}
