// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: videos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (game_id, player_id, video_url, submitted_at)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, player_id, video_url, submitted_at
`

type CreateVideoParams struct {
	GameID      pgtype.Int8      `json:"game_id"`
	PlayerID    pgtype.Int8      `json:"player_id"`
	VideoUrl    string           `json:"video_url"`
	SubmittedAt pgtype.Timestamp `json:"submitted_at"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.GameID,
		arg.PlayerID,
		arg.VideoUrl,
		arg.SubmittedAt,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.VideoUrl,
		&i.SubmittedAt,
	)
	return i, err
}

const getVideosByGame = `-- name: GetVideosByGame :many
SELECT id, game_id, player_id, video_url, submitted_at
FROM videos
WHERE game_id = $1
`

func (q *Queries) GetVideosByGame(ctx context.Context, gameID pgtype.Int8) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.VideoUrl,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosByPlayer = `-- name: GetVideosByPlayer :one
SELECT id, game_id, player_id, video_url, submitted_at
FROM videos
WHERE game_id = $1 AND player_id = $2
`

type GetVideosByPlayerParams struct {
	GameID   pgtype.Int8 `json:"game_id"`
	PlayerID pgtype.Int8 `json:"player_id"`
}

func (q *Queries) GetVideosByPlayer(ctx context.Context, arg GetVideosByPlayerParams) (Video, error) {
	row := q.db.QueryRow(ctx, getVideosByPlayer, arg.GameID, arg.PlayerID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.VideoUrl,
		&i.SubmittedAt,
	)
	return i, err
}
