// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: votes.sql

package db

import (
	"context"
)

const createVote = `-- name: CreateVote :one
INSERT INTO votes (game_id, video_id, voter_id, value, is_actual)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, game_id, video_id, voter_id, value, is_actual, voted_at
`

type CreateVoteParams struct {
	GameID   int64     `json:"game_id"`
	VideoID  int64     `json:"video_id"`
	VoterID  int64     `json:"voter_id"`
	Value    VoteValue `json:"value"`
	IsActual bool      `json:"is_actual"`
}

func (q *Queries) CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, createVote,
		arg.GameID,
		arg.VideoID,
		arg.VoterID,
		arg.Value,
		arg.IsActual,
	)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.VideoID,
		&i.VoterID,
		&i.Value,
		&i.IsActual,
		&i.VotedAt,
	)
	return i, err
}

const getVoteCountsByVideo = `-- name: GetVoteCountsByVideo :many
SELECT video_id, COUNT(*) AS vote_count
FROM votes
WHERE game_id = $1
GROUP BY video_id
`

type GetVoteCountsByVideoParams struct {
	GameID int64 `json:"game_id"`
}

type GetVoteCountsByVideoRow struct {
	VideoID   int64 `json:"video_id"`
	VoteCount int64 `json:"vote_count"`
}

func (q *Queries) GetVoteCountsByVideo(ctx context.Context, arg GetVoteCountsByVideoParams) ([]GetVoteCountsByVideoRow, error) {
	rows, err := q.db.Query(ctx, getVoteCountsByVideo, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVoteCountsByVideoRow
	for rows.Next() {
		var i GetVoteCountsByVideoRow
		if err := rows.Scan(&i.VideoID, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVotesByGame = `-- name: GetVotesByGame :many
SELECT id, game_id, video_id, voter_id, value, is_actual, voted_at
FROM votes
WHERE game_id = $1
`

type GetVotesByGameParams struct {
	GameID int64 `json:"game_id"`
}

func (q *Queries) GetVotesByGame(ctx context.Context, arg GetVotesByGameParams) ([]Vote, error) {
	rows, err := q.db.Query(ctx, getVotesByGame, arg.GameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vote
	for rows.Next() {
		var i Vote
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.VideoID,
			&i.VoterID,
			&i.Value,
			&i.IsActual,
			&i.VotedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWinningVideo = `-- name: GetWinningVideo :one
SELECT video_id, COUNT(*) AS vote_count
FROM votes
WHERE game_id = $1
GROUP BY video_id
ORDER BY vote_count DESC
LIMIT 1
`

type GetWinningVideoParams struct {
	GameID int64 `json:"game_id"`
}

type GetWinningVideoRow struct {
	VideoID   int64 `json:"video_id"`
	VoteCount int64 `json:"vote_count"`
}

func (q *Queries) GetWinningVideo(ctx context.Context, arg GetWinningVideoParams) (GetWinningVideoRow, error) {
	row := q.db.QueryRow(ctx, getWinningVideo, arg.GameID)
	var i GetWinningVideoRow
	err := row.Scan(&i.VideoID, &i.VoteCount)
	return i, err
}

const hasPlayerVoted = `-- name: HasPlayerVoted :one
SELECT EXISTS (
    SELECT 1 FROM votes
    WHERE game_id = $1 AND voter_id = $2
) AS exists
`

type HasPlayerVotedParams struct {
	GameID  int64 `json:"game_id"`
	VoterID int64 `json:"voter_id"`
}

func (q *Queries) HasPlayerVoted(ctx context.Context, arg HasPlayerVotedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPlayerVoted, arg.GameID, arg.VoterID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const invalidateOtherVotes = `-- name: InvalidateOtherVotes :exec
UPDATE votes SET is_actual = FALSE WHERE game_id = $1 AND video_id = $2 AND voter_id = $3 AND id <> $4
`

type InvalidateOtherVotesParams struct {
	GameID  int64 `json:"game_id"`
	VideoID int64 `json:"video_id"`
	VoterID int64 `json:"voter_id"`
	ID      int64 `json:"id"`
}

func (q *Queries) InvalidateOtherVotes(ctx context.Context, arg InvalidateOtherVotesParams) error {
	_, err := q.db.Exec(ctx, invalidateOtherVotes,
		arg.GameID,
		arg.VideoID,
		arg.VoterID,
		arg.ID,
	)
	return err
}
