// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package qg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Player struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Theme struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Video struct {
	ID       int64              `json:"id"`
	PlayerID int64              `json:"player_id"`
	VideoUrl string             `json:"video_url"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
}

type VideoRequest struct {
	ID        int64              `json:"id"`
	Request   string             `json:"request"`
	ThemeID   int64              `json:"theme_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
