// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: utils.sql

package qg

import (
	"context"
)

const acquireAdvisoryXactLock = `-- name: AcquireAdvisoryXactLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

type AcquireAdvisoryXactLockParams struct {
	Column1 int64 `json:"column_1"`
}

// Blocks until acquired; auto-released when the current transaction ends.
func (q *Queries) AcquireAdvisoryXactLock(ctx context.Context, arg AcquireAdvisoryXactLockParams) error {
	_, err := q.db.Exec(ctx, acquireAdvisoryXactLock, arg.Column1)
	return err
}
