// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: videos.sql

package qg

import (
	"context"
	"encoding/json"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (player_id, video_url, oembed) VALUES ($1, $2, $3) RETURNING id, player_id, video_url, oembed, added_at
`

type CreateVideoParams struct {
	PlayerID int64           `json:"player_id"`
	VideoUrl string          `json:"video_url"`
	Oembed   json.RawMessage `json:"oembed"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.PlayerID, arg.VideoUrl, arg.Oembed)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.VideoUrl,
		&i.Oembed,
		&i.AddedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, player_id, video_url, oembed, added_at FROM videos WHERE id = $1
`

type GetVideoParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) GetVideo(ctx context.Context, arg GetVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, arg.ID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.VideoUrl,
		&i.Oembed,
		&i.AddedAt,
	)
	return i, err
}

const getVideosByPlayer = `-- name: GetVideosByPlayer :many
SELECT id, player_id, video_url, oembed, added_at FROM videos WHERE player_id = $1
`

type GetVideosByPlayerParams struct {
	PlayerID int64 `json:"player_id"`
}

func (q *Queries) GetVideosByPlayer(ctx context.Context, arg GetVideosByPlayerParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByPlayer, arg.PlayerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.VideoUrl,
			&i.Oembed,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
